apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snake-backend-hpa
  namespace: snake-game
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snake-backend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snake-frontend-hpa
  namespace: snake-game
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snake-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
